### ISSUE TITLE
Release Version v1.1.1

### ISSUE THREAD

**Issue by julianbrost** [Icinga/icingadb#628]
# Release Workflow

- [x] Check that the `.mailmap` and `AUTHORS` files are up to date: #629
- [x] Update `internal/version.go`: #629
- [x] Update `CHANGELOG.md`: #629
- [x] Create and push a signed tag for the version: [v1.1.1](https://github.com/Icinga/icingadb/releases/tag/v1.1.1)
- [x] Build packages:
- [x] Create release on GitHub
- [x] Update public docs
- [x] Announce release
